# Generated by Django 2.2.3 on 2019-07-05 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.CharField(max_length=250)),
                ('Company', models.TextField(default='Not Available', max_length=250)),
                ('Address', models.TextField(default='Not available', max_length=250)),
                ('Deadline', models.DateField(default=django.utils.timezone.now)),
                ('URL', models.URLField(blank=True, db_index=True, max_length=128)),
            ],
            options={
                'ordering': ('-Deadline',),
            },
        ),
    ]
