# Generated by Django 2.1.7 on 2019-07-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190713_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='Company',
        ),
        migrations.AddField(
            model_name='jobs',
            name='employmentType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Address',
            field=models.TextField(max_length=250),
        ),
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ManyToManyField(to='core.Company'),
        ),
    ]
